---
name: Build and Push Docker Image to Google Cloud Platform
on: 
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: carro-app-backend
      PROJECT_ID: pro-bliss-413511
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with: 
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker buildx build --platform linux/amd64 -t carro-backend-api:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        gcloud auth print-access-token
        docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev

    # - name: Push Docker Image to Container Registry (GCR)
    #   run: |-
    #     docker tag carro-backend-api:latest gcr.io/$PROJECT_ID/carro-backend-api:latest
    #     docker push gcr.io/$PROJECT_ID/carro-backend-api:latest

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag carro-backend-api:latest us-central1-docker.pkg.dev/$PROJECT_ID/carro-backend-api/carro-backend-api:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/carro-backend-api/carro-backend-api:latest

    # - name: Push Docker Image to Container Registry (GCR)
    #   env:
    #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
    #   run: |-
    #     docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #     docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    #     docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #     docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    # - name: Push Docker Image to Artifact Registry
    #   env:
    #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
    #   run: |-
    #     docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:latest
    #     docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$GIT_TAG
    #     docker push us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:latest
    #     docker push us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$GIT_TAG